const products = [
    {
        _id: '1',
        name: 'prod 1',
        image: '/.jpg',
        description: 'lorrem ipsum',
        brand: 'brand 1',
        category: 'category 1',
        price: 10,
        countInStock: 3,
        rating: 4.5,
        numReviews: 1,
    },
    {
        _id: '2',
        name: 'prod 2',
        image: '/.jpg',
        description: 'lorrem ipsum',
        brand: 'brand 2',
        category: 'category 2',
        price: 20,
        countInStock: 3,
        rating: 4.5,
        numReviews: 2,
    },
    {
        _id: '3',
        name: 'prod 3',
        image: '/.jpg',
        description: 'lorrem ipsum',
        brand: 'brand 3',
        category: 'category 3',
        price: 30,
        countInStock: 3,
        rating: 4.5,
        numReviews: 3,
    },
    {
        _id: '4',
        name: 'prod 4',
        image: '/.jpg',
        description: 'lorrem ipsum',
        brand: 'brand 4',
        category: 'category 4',
        price: 40,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '5',
        name: 'prod 5',
        image: '/.jpg',
        description: 'lorrem ipsum',
        brand: 'brand 5',
        category: 'category 5',
        price: 50,
        countInStock: 5,
        rating: 4.5,
        numReviews: 5,
    },
]